// Package swagger_docs Code generated by swaggo/swag. DO NOT EDIT
package swagger_docs

import "github.com/swaggo/swag"

const docTemplatestandard = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache-2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/applications": {
            "get": {
                "description": "List host applications.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Host Applications"
                ],
                "summary": "List applications",
                "responses": {
                    "200": {
                        "description": "host applications",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.HostApplication"
                            }
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Add a host application.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Host Applications"
                ],
                "summary": "Add application",
                "parameters": [
                    {
                        "description": "application information",
                        "name": "endpoint",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.HostApplicationBase"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/applications/{id}": {
            "delete": {
                "description": "Remove a host application.",
                "tags": [
                    "Host Applications"
                ],
                "summary": "Delete application",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/blacklists/net-interfaces": {
            "get": {
                "description": "List blacklisted host network interfaces.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Blacklists"
                ],
                "summary": "List network interfaces",
                "responses": {
                    "200": {
                        "description": "network interfaces",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Add a host network interface to the list.",
                "consumes": [
                    "text/plain"
                ],
                "tags": [
                    "Blacklists"
                ],
                "summary": "Add network interface",
                "parameters": [
                    {
                        "description": "interface name",
                        "name": "value",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove a host network interface from the list.",
                "tags": [
                    "Blacklists"
                ],
                "summary": "Delete network interface",
                "parameters": [
                    {
                        "type": "string",
                        "description": "interface name",
                        "name": "value",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/blacklists/net-ranges": {
            "get": {
                "description": "List blacklisted network ranges.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Blacklists"
                ],
                "summary": "List network ranges",
                "responses": {
                    "200": {
                        "description": "network rages",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Add a network range to the list.",
                "consumes": [
                    "text/plain"
                ],
                "tags": [
                    "Blacklists"
                ],
                "summary": "Add network range",
                "parameters": [
                    {
                        "description": "network range in CIDR notation",
                        "name": "value",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove a network range from the list.",
                "tags": [
                    "Blacklists"
                ],
                "summary": "Delete network range",
                "parameters": [
                    {
                        "type": "string",
                        "description": "network range",
                        "name": "value",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/host-info": {
            "get": {
                "description": "Get host information.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Host Information"
                ],
                "summary": "Get all",
                "responses": {
                    "200": {
                        "description": "host info",
                        "schema": {
                            "$ref": "#/definitions/model.HostInfo"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/host-info/network": {
            "get": {
                "description": "Get host network information.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Host Information"
                ],
                "summary": "Get network",
                "responses": {
                    "200": {
                        "description": "host network info",
                        "schema": {
                            "$ref": "#/definitions/model.HostNet"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/host-resources": {
            "get": {
                "description": "List host resources like application sockets or serial adapters.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Host Resources"
                ],
                "summary": "List resources",
                "responses": {
                    "200": {
                        "description": "host resources",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.HostResource"
                            }
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/host-resources/{id}": {
            "get": {
                "description": "Get a host resource.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Host Resources"
                ],
                "summary": "Get resource",
                "parameters": [
                    {
                        "type": "string",
                        "description": "resource id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "host resources",
                        "schema": {
                            "$ref": "#/definitions/model.HostResource"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/info": {
            "get": {
                "description": "Get basic service and runtime information.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service Information"
                ],
                "summary": "Get stats",
                "responses": {
                    "200": {
                        "description": "info",
                        "schema": {
                            "$ref": "#/definitions/lib.SrvInfo"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "lib.MemStats": {
            "type": "object",
            "properties": {
                "alloc": {
                    "type": "integer"
                },
                "alloc_total": {
                    "type": "integer"
                },
                "gc_cycles": {
                    "type": "integer"
                },
                "sys_total": {
                    "type": "integer"
                }
            }
        },
        "lib.SrvInfo": {
            "type": "object",
            "properties": {
                "mem_stats": {
                    "$ref": "#/definitions/lib.MemStats"
                },
                "name": {
                    "type": "string"
                },
                "up_time": {
                    "$ref": "#/definitions/time.Duration"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "model.HostApplication": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "socket": {
                    "type": "string"
                }
            }
        },
        "model.HostApplicationBase": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "socket": {
                    "type": "string"
                }
            }
        },
        "model.HostInfo": {
            "type": "object",
            "properties": {
                "hardware": {},
                "network": {
                    "$ref": "#/definitions/model.HostNet"
                },
                "os": {}
            }
        },
        "model.HostNet": {
            "type": "object",
            "properties": {
                "hostname": {
                    "type": "string"
                },
                "interfaces": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.NetInterface"
                    }
                }
            }
        },
        "model.HostResource": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "$ref": "#/definitions/model.ResourceType"
                }
            }
        },
        "model.NetInterface": {
            "type": "object",
            "properties": {
                "ipv4_addr": {
                    "type": "string"
                },
                "ipv4_mask": {
                    "type": "string"
                },
                "ipv4_net": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.ResourceType": {
            "type": "string",
            "enum": [
                "serial",
                "app"
            ],
            "x-enum-varnames": [
                "SerialDevice",
                "Application"
            ]
        },
        "time.Duration": {
            "type": "integer",
            "enum": [
                1,
                1000,
                1000000,
                1000000000
            ],
            "x-enum-varnames": [
                "Nanosecond",
                "Microsecond",
                "Millisecond",
                "Second"
            ]
        }
    }
}`

// SwaggerInfostandard holds exported Swagger Info so clients can modify it
var SwaggerInfostandard = &swag.Spec{
	Version:          "1.3.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Host Manager API",
	Description:      "Provides access to host functions.",
	InfoInstanceName: "standard",
	SwaggerTemplate:  docTemplatestandard,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfostandard.InstanceName(), SwaggerInfostandard)
}
