name: Build, Test & Upload

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Build
        run: CGO_ENABLED=0 GOOS=linux go build -o manager -ldflags="-X 'main.version=${{ github.ref_name }}'" main.go
#      - name: Test
#        run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
      - uses: actions/upload-artifact@v3
        with:
          name: manager_${{ github.ref_name }}
          path: manager

